### ISSUE TITLE
die/exit is not support swoole

### ISSUE THREAD

**Issue by soyleung** [n0nag0n/fatfree-swoole#2]
First，good luck evryone!!
How want to solve F3 - > reroute use die, it does not support swoole！
How do you think about it！！！

**Comment by soyleung** [comment]
i try it,
1>
In f3 Base reroute class ,
`if ($this->hive['CLI'])
			$this->mock('GET '.$url.' [cli]');
`
+++ after 
 `
		elseif ($this->hive['SWOOLE']) {
			$status = $this->status($permanent?301:302);
			$this->hive['REROUTE'] = $url.','.$status;
		}`
2> 
In convertToFatFreeRequest class
`$fw->set('CLI', FALSE);`
+++after
`$fw->set('SWOOLE', TRUE);`
3>
In convertToSwooleResponse class
+++
		if ($fw->REROUTE)
			$swooleResponse->redirect($fw->REROUTE);
more die/exit is not support swoole will try this idea

**Comment by n0nag0n** [comment]
Do that in a pull request and change the readme file for your changes and I'll pull it in.Thanks for the help!

**Comment by soyleung** [comment]
this is no good idea!! I just found!!!
it can use ONREROUTE to redirect url!!! It's going to work really well.


`$f3->set('ONREROUTE',function($url,$permanent) use ($swooleResponse){
	$swooleResponse->redirect($url);
	// do something
});`

**Comment by n0nag0n** [comment]
Great solution!

**Comment by n0nag0n** [comment]
I added it to the example index.php file

**Comment by soyleung** [comment]
TKS,Bro!! 
More and more bugs in the f-swoole, I will be want try to fix!

**Comment by n0nag0n** [comment]
Hey @soyleung I noticed in your FS repo you forked from this one, you mentioned this line:
```
New: https://github.com/DpodoNetwork/DSF
```
Is that a private repo?

**Comment by soyleung** [comment]
I have the idea of reframing it to make it more friendly.

**Comment by n0nag0n** [comment]
Ahh ok. I just don't have access to whatever that repo is @soyleung haha
